# Supabase Configuration File

# Project settings
project_id = "YOUR_PROJECT_ID"

[api]
  enabled = true
  port = 54321
  schemas = ["public", "app", "ledger"]
  extra_search_path = ["public", "app", "ledger"]
  max_rows = 1000

[db]
  port = 54322
  major_version = 15

[studio]
  enabled = true
  port = 54323

# Edge Functions runtime settings
[functions]
  import_map = "./import_map.json"

# Auth settings (optional - configure in Supabase dashboard)
[auth]
  enabled = true
  site_url = "http://localhost:3000"

# Storage settings (optional)
[storage]
  enabled = false
